gtk2/roadmap_canvas_agg.cpp: fixing truncated casting c++ error
Fix truncated casting:

roadmap_canvas_agg.cpp:254:18: error: cast from ‘void*’ to ‘int’ loses
precision

Use c99 pointer type instead of int.

Signed-off-by: Sasha Khapyorsky <sashakh@gmail.com>